services:

  nginx:
    image: nginx:1.15.12-alpine
    restart: unless-stopped
    ports:
      - "8083:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./wp-data:/var/www/html
    networks:
      - wordpress-network
  database:
    image: mariadb:10
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    ports: ['3306:3306'] 
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: 'abc@123'
    networks:
      - wordpress-network
  wordpress:
    container_name: wordpress
    depends_on: 
      - 'database'
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: '${DB_HOST}:3306'
      WORDPRESS_DB_NAME: '${DB_NAME}'
      WORDPRESS_DB_USER: '${DB_USER}'
      WORDPRESS_DB_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ./wp-data:/var/www/html:rw
    networks:
      - wordpress-network
  phpadmin:
    depends_on: 
      - 'database'
    image: phpmyadmin/phpmyadmin:4.7
    container_name: phpadmin
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PMA_HOST: '${DB_HOST}'
      PMA_PORT: 3306  
      MYSQL_ROOT_PASSWORD: 'abc@123'
    networks:
      - wordpress-network

volumes:
  db_data: {}
 
networks:
  wordpress-network:
    driver: bridge
